CREATE TABLE IF NOT EXISTS `estado_jogo` (
  `id_estado_jogo` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `descricao` VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS `estado_transacao` (
  `id_estado_transacao` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `descricao` VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS `metodo_envio` (
  `id_metodo_envio` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `descricao` VARCHAR(150) NOT NULL
);